In [27]:
import numpy as np

X  = [[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]

class Layer:
    def __init__(self, n_inputs, n_neurons):
        self.output = None
        self.weights = 0.1 * np.random.rand(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [30]:
layer1 = Layer(4, 5)
layer2 = Layer(5, 2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[0.2625978  0.36105712 0.30036264 0.35005712 0.33728962]
 [0.18333014 0.17146306 0.50006113 0.42031256 0.24732719]
 [0.01134853 0.28983898 0.29676899 0.10780243 0.11048147]]
[[0.08291099 0.05496327]
 [0.07498729 0.04824417]
 [0.02151217 0.03257322]]
